
image: gitpod/workspace-java-17
tasks:
  - before: docker run -d -p5433:5433 -p15433:15433 yugabytedb/yugabyte yugabyted start --background=false
  - init: mvn spring-boot:run
  #- init: ./mvnw install -DskipTests=false


